version: '3.8'

services:
  ui:
    build: ./ui
    depends_on:
      - app
    ports:
      - "80:80"
  app:
    build: ./app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=app_db
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: ./db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1"]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

